name: E2E Tests

# Controls when the action will run. 
on:
  # Triggers the workflow on pull request events for dev and main
  pull_request:
    branches: [ main ]
  # Manual trigger API Tests
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'     
        required: true
        default: 'warning'
      tags:
        description: 'Run Cypress E2E Tests'

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains one job "test"
  test:
    # The type of runner that the job will run on
    runs-on: ubuntu-16.04

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout
        uses: actions/checkout@v2

      # Will need later for external API's
      - name: Make envfile
        uses: SpicyPizza/create-envfile@v1
        with:
          envkey_AUTH_USERNAME: ${{ secrets.AUTH_USERNAME }}
          envkey_AUTH_PASSWORD: ${{ secrets.AUTH_PASSWORD }}

      # Runs a single command using the runners shell
      - name: Cypress run
        uses: cypress-io/github-action@v2
        with:
          start: npm start
          wait-on: http://localhost:3000
          browser: chrome
          headless: true
          spec: cypress/integration/*.spec.js
